spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      uri: ${DB_URI}
      database: ${DB_NAME}
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-milliseconds: ${JWT_VALIDITY_TIME}
api:
  key:
    seoul: ${SEOUL_API_KEY}
    sk: ${SK_API_KEY}