spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      uri: ${DB_URI}
      database: ${DB_NAME}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-milliseconds: ${JWT_VALIDITY_TIME}
  refresh-token-validity-in-milliseconds: ${JWT_REFRESH_VALIDITY_TIME}
api:
  key:
    seoul: ${SEOUL_API_KEY}
    sk: ${SK_API_KEY}
    path: ${SUBWAY_PATH_API_KEY}
logging:
  level:
    root: TRACE